### PR TITLE
🩹 bugfix - 350 - Waveform clipping at starting position

### LINKED ISSUE #350: Audio waveform clipping on the left side during recording in Flutter app
**Describe the bug**
The audio waveform is not rendering correctly in the app, and it appears to be cut off on the left side. I have attached a screenshot below to illustrate the issue.

**To Reproduce**
`Widget build(BuildContext context) {
    return Scaffold(
        appBar: _appbar(widget.meeting),
        body: Padding(
          padding: EdgeInsets.only(left: 20),
          child: recordControls(),
        ));
  }

  Widget recordControls() {
    try {
      return AudioWaveforms(
        enableGesture: false,
        size: Size(double.infinity, 80),
        recorderController: _recorderController,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12.0),
          color: Colors.transparent,
        ),
        waveStyle: WaveStyle(
          extendWaveform: true,
          spacing: 21,
          scaleFactor: 200,
          showMiddleLine: false,
          waveColor: AppUtils.isDarkTheme(context)
              ? Colors.white
              : Colors.grey.shade800,
          waveCap: StrokeCap.round,
          waveThickness: 5.0,
        ),
      );
    } catch (e) {
      Trace.trackException(
          error: e, location: "RecordMeetingDashboard_recordControls");
      return Container();
    }
  }`

**Expected behavior**
The waveform should render completely from the left side without any clipping.

**Smartphone (please complete the following information):**
Android and ios

**Screenshots**
image

**Additional context**
AudioWaveforms package version:   audio_waveforms: ^1.1.1

### PR DESCRIPTION
**Pull request by jay-simformsolutions**
Fix #350

### CODE REVIEW

File: lib/src/audio_waveforms.dart [hunk 1]
```diff
@@ -41,7 +41,7 @@ class _AudioWaveformsState extends State<AudioWaveforms> {
   Offset _dragOffset = Offset.zero;
 
   double _initialOffsetPosition = 0.0;
-  double _initialPosition = 0.0;
+  double _initialPosition = 3.0;
```
Comment (ujas-m-simformsolutions) [inline lib/src/audio_waveforms.dart:44]: Dont use static values. What if I set waveThickness too large wouldn't the wave get outside of the viewport?

**Review by ujas-m-simformsolutions — APPROVED** [review]
