### PR TITLE
fix: 🐛 Added support for Ios Linear PCM Codec

### LINKED ISSUE #309: IosEncoder Linear PCM is not supported we get Platform Exception but it doesnt say why
only MPEG4AAC format of ios is working

### PR DESCRIPTION
**Pull request by manoj-simform**
Fixed #309.

### CODE REVIEW

File: example/lib/main.dart [hunk 1]
```diff
@@ -53,11 +53,7 @@ class _HomeState extends State<Home> {
   }
 
   void _initialiseControllers() {
-    recorderController = RecorderController()
-      ..androidEncoder = AndroidEncoder.aac
-      ..androidOutputFormat = AndroidOutputFormat.mpeg4
-      ..iosEncoder = IosEncoder.kAudioFormatMPEG4AAC
-      ..sampleRate = 44100;
+    recorderController = RecorderController();
```
Comment (ujas-m-simformsolutions) [inline example/lib/main.dart:56]: Please add default parameter for example

File: ios/Classes/SwiftAudioWaveformsPlugin.swift [hunk 2]
```diff
@@ -27,8 +27,10 @@ public class SwiftAudioWaveformsPlugin: NSObject, FlutterPlugin {
         let args = call.arguments as? Dictionary<String, Any>
         switch call.method {
         case Constants.startRecording:
-            audioRecorder.startRecording(result,  args?[Constants.path] as? String,
-                                         args?[Constants.encoder] as? Int, args?[Constants.sampleRate] as? Int, args?[Constants.bitRate] as? Int,Constants.fileNameFormat, args?[Constants.useLegacyNormalization] as? Bool,overrideAudioSession: (args?[Constants.overrideAudioSession] as? Bool) ?? true )
+            guard let args = call.arguments as? Dictionary<String, Any> else {
```
Comment (ujas-m-simformsolutions) [inline ios/Classes/SwiftAudioWaveformsPlugin.swift:30]: Add error in this block so that user can identify the error

**Review by ujas-m-simformsolutions — APPROVED** [review]
