### PR TITLE
:bug: Fixed android volume error 

### LINKED ISSUE #101: Android volume exception :  .ClassCastException: java.lang.Double cannot be cast to java.lang.Float
Thanks a lot for this great package. 

However while I tried to use
 ```
if (playerController.playerState == PlayerState.playing) {
        playerController.setVolume(0.0);
}
``` 
 I got an error cast from android with double & float : 
 
```
I/flutter (32185): │ ⛔ Error from outside Flutter : PlatformException(error, java.lang.Double cannot be cast to java.lang.Float, null, java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
I/flutter (32185): │ ⛔ 	at com.simform.audio_waveforms.AudioWaveformsPlugin.onMethodCall(AudioWaveformsPlugin.kt:124)
I/flutter (32185): │ ⛔ 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I/flutter (32185): │ ⛔ 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
I/flutter (32185): │ ⛔ 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter (32185): │ ⛔ 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (32185): │ ⛔ 	at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (32185): │ ⛔ 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (32185): │ ⛔ 	at android.os.Looper.loop(Looper.java:250)
I/flutter (32185): │ ⛔ 	at android.app.ActivityThread.main(ActivityThread.java:7755)
I/flutter (32185): │ ⛔ 	at java.lang.reflect.Method.invoke(Native Method)
I/flutter (32185): │ ⛔ 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
I/flutter (32185): │ ⛔ 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
I/flutter (32185): │ ⛔ ) 
I/flutter (32185): │ ⛔  #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
I/flutter (32185): │ ⛔ #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
I/flutter (32185): │ ⛔ <asynchronous suspension>
I/flutter (32185): │ ⛔ #2      AudioWaveformsInterface.setVolume (package:audio_waveforms/src/base/audio_waveforms_interface.dart:132:18)
I/flutter (32185): │ ⛔ <asynchronous suspension>
I/flutter (32185): │ ⛔ #3      PlayerController.setVolume (package:audio_waveforms/src/controllers/player_controller.dart:158:20)
I/flutter (32185): │ ⛔ <asynchronous suspension>
I/flutter (32185): │ ⛔ 
I/flutter (32185): 
```

I tried with int and double but got the same result 
Thanks for any help

### PR DESCRIPTION
**Pull request by Ujas-Majithiya**
* Fixed zero duration would cause waveforms not to expand
* Fixed `postFrameCallback` error for flutter version below 3.0.0
* Updated default values for bitRate and sampleRate

Fixes #101

### CODE REVIEW

**Comment by VivekMakwana24** [comment]
@Ujas-Majithiya 

Could you please merge this and release the new version asap?

We are facing this issue while managing volume on Android.

File: lib/src/audio_waveforms.dart [hunk 1]
```diff
@@ -173,7 +173,7 @@ class _AudioWaveformsState extends State<AudioWaveforms> {
       _totalBackDistance = Offset.zero;
       _dragOffset = Offset.zero;
     }
-    WidgetsBinding.instance.addPostFrameCallback((_) {
+    ambiguate(WidgetsBinding.instance)?.addPostFrameCallback((_) {
```
Comment (ShwetaChauhan18) [inline lib/src/audio_waveforms.dart:176]: what is the purpose of this?? ambiguate

**Review by ShwetaChauhan18 — APPROVED** [review]
LGTM
