### PR TITLE
fix: 🐛 Cannot catch error of preparePlayer (#301)

### LINKED ISSUE #301: Cannot catch error of preparePlayer
**Describe the bug**
When an error is thrown by `controller.preparePlayer`, it cannot be caught. Experiencing this on Android, have not tested on iOS.

For example, when trying to play a file in an invalid format on Android, the console shows the error:

```
Playback error
com.google.android.exoplayer2.ExoPlaybackException: Source error
```

However, a try/catch block or `catchError` does not fire, and the code is blocked without further execution.

**To Reproduce**
1. Run `controller.preparePlayer` using an invalid file
2. Try to catch error using `catchError` or try/catch block.
3. Catch does not work

**Expected behavior**
Catch should catch any player errors and continue code execution.

### PR DESCRIPTION
**Pull request by jay-simformsolutions**
Fixed #301

### CODE REVIEW

File: android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt [hunk 1]
```diff
@@ -42,6 +41,12 @@ class AudioPlayer(
             player?.addMediaItem(mediaItem)
             player?.prepare()
             playerListener = object : Player.Listener {
+
+                override fun onPlayerError(error: com.google.android.exoplayer2.PlaybackException) {
```
Comment (ujas-m-simformsolutions) [inline android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt:45]: I think we can import this and just use type here

File: android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt [hunk 2]
```diff
@@ -42,6 +41,12 @@ class AudioPlayer(
...
+                    super.onPlayerError(error)
+                    result.error(Constants.LOG_TAG, error.message, "Exo-Player Error")
```
Comment (ujas-m-simformsolutions) [inline android/src/main/kotlin/com/simform/audio_waveforms/AudioPlayer.kt:47]: `Exo player error` doesn't look informative.

File: example/pubspec.yaml [hunk 3]
```diff
@@ -61,7 +64,7 @@ flutter:
    - assets/audios/audio2.mp3
    - assets/audios/audio3.mp3
    - assets/audios/audio4.mp3
-
+   - assets/audios/audio5.mp3
```
Comment (ujas-m-simformsolutions) [inline example/pubspec.yaml:67]: Did you forget to remove it?

**Review by ujas-m-simformsolutions — CHANGES_REQUESTED** [review]

**Review by ujas-m-simformsolutions — APPROVED** [review]
