### PR TITLE
fix: 🐛️ Waveform extraction stuck at 99%

### LINKED ISSUE #390: Continuous waveform: false doesn't display anything even after extraction is done
**Describe the bug**
When set to false, waveform doesn't show.

**Expected behavior**
Display waveform after extraction

**Smartphone (please complete the following information):**
- Device: Samsung s10 5g
- OS: Android 11

AudioFileWaveforms(
                                        playerController: playerController,
                                        waveformType: WaveformType.fitWidth,
                                        continuousWaveform: false,
                                        playerWaveStyle: const PlayerWaveStyle(
                                            liveWaveColor: Colors.black,
                                            fixedWaveColor: Colors.black),
                                        size: const Size(200, 30),
                                      ),

when set to true, it works okay. But I'd rather show users the wave form when everything is ready, hence disabling the continuousWaveform, but it doesn't work.  It was also tested on a 3 seconds audio not a large audio that would take time to extract.

### PR DESCRIPTION
**Pull request by ujas-m-simformsolutions**
Fixes #390

### CODE REVIEW

File: android/src/main/kotlin/com/simform/audio_waveforms/WaveformExtractor.kt [hunk 1]
```diff
@@ -220,17 +209,38 @@ class WaveformExtractor(
             val second = buf.get().toLong() shl 8
             val third = buf.get().toLong() shl 16
             val forth = buf.get().toLong() shl 24
-            val value = (first or second or third or forth) / 2147483648f
+            val value = (first or second or third or forth) / 2.14748365E9f
```
Comment (vatsaltanna-simformsolutions) [inline android/src/main/kotlin/com/simform/audio_waveforms/WaveformExtractor.kt:212]: Please write reason for using this pertucular value on top of it.

**Review by vatsaltanna-simformsolutions — APPROVED** [review]
