### PR TITLE
fix: :bug: unnecessary rendering

### LINKED ISSUE #232: rendering the entire waveform data is not necissary and it becomes very slow when your waveform data is long
rerendering only the visible is enough

### PR DESCRIPTION
**Pull request by ujas-m-simformsolutions**
This PR adds conditions to rendering function so that it only renders when required. And also adds conditions to duration label list so that it doesn't add to many unnecessary labels.
Fixes #232

### CODE REVIEW

File: lib/src/painters/player_wave_painter.dart [hunk 1]
```diff
@@ -92,35 +92,32 @@ class PlayerWavePainter extends CustomPainter {
...
+          totalBackDistance.dx +
+          emptySpace +
+          (waveformType.isFitWidth ? 0 : halfWidth);
+      final bottomDy = halfHeight +
+          (showBottom
+              ? ((waveformData[i] * animValue)) * scaleFactor * scrollScale
+              : 0);
+      final topDy = halfHeight +
+          (showTop
+              ? -((waveformData[i] * animValue)) * scaleFactor * scrollScale
```
Comment (aditya-css) [inline lib/src/painters/player_wave_painter.dart:112]: The calculation `-((waveformData[i] * animValue)) * scaleFactor * scrollScale` is repeated above as well, with only difference of polarity of the final result. Please extract to a common variable.

File: lib/src/painters/player_wave_painter.dart [hunk 2]
```diff
@@ -92,35 +92,32 @@ class PlayerWavePainter extends CustomPainter {
...
-        i < audioProgress * length ? liveWavePaint : fixedWavePaint,
-      );
+      final dx = i * spacing +
+          dragOffset.dx -
+          totalBackDistance.dx +
+          emptySpace +
+          (waveformType.isFitWidth ? 0 : halfWidth);
+      final bottomDy = halfHeight +
+          (showBottom
+              ? ((waveformData[i] * animValue)) * scaleFactor * scrollScale
```
Comment (aditya-css) [inline lib/src/painters/player_wave_painter.dart:108]: Unnecessary duplicate brackets `((waveformData[i] * animValue))`.

File: lib/src/painters/recorder_wave_painter.dart [hunk 3]
```diff
@@ -95,13 +97,14 @@ class RecorderWavePainter extends CustomPainter {
   var _labelPadding = 0.0;
 
   final List<Label> _labels = [];
+  static const durationBuffer = 5;
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:100]: Specify type for members of public API or make the field private.

File: lib/src/painters/recorder_wave_painter.dart [hunk 4]
```diff
@@ -137,48 +137,48 @@ class RecorderWavePainter extends CustomPainter {
...
+    final labelDuration = Duration(seconds: i);
+    final durationLineDx = _labelPadding + dragOffset.dx - totalBackDistance.dx;
+
+    if (labelDuration <
+        Duration(
+            seconds: currentlyRecordedDuration.inSeconds + durationBuffer)) {
+      canvas.drawLine(
+          Offset(durationLineDx, size.height),
+          Offset(durationLineDx, size.height + durationLinesHeight),
+          _durationLinePaint);
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:171]: format

File: lib/src/painters/recorder_wave_painter.dart [hunk 5]
```diff
@@ -137,48 +137,48 @@ class RecorderWavePainter extends CustomPainter {
...
+      _labels.add(
+        Label(
+          content: showHourInDuration
+              ? labelDuration.toHHMMSS()
+              : labelDuration.inSeconds.toMMSS(),
+          offset: Offset(
+              durationLineDx - durationTextPadding, size.height + labelSpacing),
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:178]: format

File: lib/src/painters/recorder_wave_painter.dart [hunk 6]
```diff
@@ -190,38 +190,19 @@ class RecorderWavePainter extends CustomPainter {
...
-        _wavePaint);
+  void _drawWave(Canvas canvas, Size size, int i) {
+    final halfWidth = size.width / 2;
+    final dx =
+        -totalBackDistance.dx + dragOffset.dx + (spacing * i) - initialPosition;
+    final upperDy = (size.height) -
+        (showTop ? (waveData[i] * scaleFactor) : 0) -
+        bottomPadding;
+    final lowerDy = size.height +
+        (showBottom ? waveData[i] * scaleFactor : 0) -
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:201]: Repeated calculation: `waveData[i] * scaleFactor`.

File: lib/src/painters/recorder_wave_painter.dart [hunk 7]
```diff
@@ -190,38 +190,19 @@ class RecorderWavePainter extends CustomPainter {
...
-                dragOffset.dx +
-                (spacing * i) -
-                initialPosition,
-            (waveData[i] * scaleFactor) + size.height - bottomPadding),
-        _wavePaint);
+  void _drawWave(Canvas canvas, Size size, int i) {
+    final halfWidth = size.width / 2;
+    final dx =
+        -totalBackDistance.dx + dragOffset.dx + (spacing * i) - initialPosition;
+    final upperDy = (size.height) -
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:197]: Unnecessary parenthesis `(size.height)`.

File: lib/src/painters/recorder_wave_painter.dart [hunk 8]
```diff
@@ -190,38 +190,19 @@ class RecorderWavePainter extends CustomPainter {
...
+        (showTop ? (waveData[i] * scaleFactor) : 0) -
+        bottomPadding;
+    final lowerDy = size.height +
+        (showBottom ? waveData[i] * scaleFactor : 0) -
+        bottomPadding;
+    if (dx > -halfWidth && dx < halfWidth * 2) {
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:203]: try to justify the application of if condition.

File: lib/src/painters/recorder_wave_painter.dart [hunk 9]
```diff
@@ -137,48 +137,48 @@ class RecorderWavePainter extends CustomPainter {
...
+      final halfWidth = size.width / 2;
       final textSpan = TextSpan(
-        text: _labels[i].content,
+        text: content,
         style: durationStyle,
       );
 
-      if (_labels[i].offset.dx > -size.width / 2 &&
-          _labels[i].offset.dx < size.width + size.width / 2) {
+      if (offset.dx > -halfWidth && offset.dx < halfWidth * 3) {
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:150]: try to justify the application of if condition.

File: lib/src/painters/player_wave_painter.dart [hunk 10]
```diff
@@ -92,35 +92,32 @@ class PlayerWavePainter extends CustomPainter {
...
+              : 0);
+      final topDy = halfHeight +
+          (showTop
+              ? -((waveformData[i] * animValue)) * scaleFactor * scrollScale
+              : 0);
+      if (dx > 0 && dx < halfWidth * 2) {
```
Comment (aditya-css) [inline lib/src/painters/player_wave_painter.dart:114]: try to justify the application of if condition.

File: lib/src/audio_waveforms.dart [hunk 11]
```diff
@@ -40,18 +40,20 @@ class _AudioWaveformsState extends State<AudioWaveforms> {
...
   double _initialPosition = 0.0;
+  Duration currentlyRecordedDuration = Duration.zero;
 
   @override
   void initState() {
     super.initState();
-    widget.recorderController.addListener(() {
-      if (mounted) setState(() {});
+    widget.recorderController.addListener(_updateOnControllerUpdate);
+    widget.recorderController.onCurrentDuration.listen((duration) {
```
Comment (aditya-css) [inline lib/src/audio_waveforms.dart:49]: cascade

File: lib/src/painters/player_wave_painter.dart [hunk 12]
```diff
@@ -92,35 +92,32 @@ class PlayerWavePainter extends CustomPainter {
...
-              (waveformType.isFitWidth ? 0 : size.width / 2),
-          size.height / 2 +
-              (showTop
-                  ? -((waveformData[i] * animValue)) * scaleFactor * scrollScale
-                  : 0),
-        ),
-        i < audioProgress * length ? liveWavePaint : fixedWavePaint,
-      );
+      final dx = i * spacing +
+          dragOffset.dx -
```
Comment (aditya-css) [inline lib/src/painters/player_wave_painter.dart:102]: create separate variables with proper naming suggesting the purpose of calculation if possible.

**Review by aditya-css — CHANGES_REQUESTED** [review]

File: lib/src/audio_waveforms.dart [hunk 13]
```diff
@@ -40,18 +40,21 @@ class _AudioWaveformsState extends State<AudioWaveforms> {
...
 
   @override
   void initState() {
     super.initState();
-    widget.recorderController.addListener(() {
-      if (mounted) setState(() {});
-    });
+    widget.recorderController
+      ..addListener(_updateOnControllerUpdate)
+      ..onCurrentDuration.listen((duration) {
```
Comment (aditya-css) [inline lib/src/audio_waveforms.dart:50]: please store the `StreamSubscription` returned by the `listen` method and cancel it when not required.

File: lib/src/painters/recorder_wave_painter.dart [hunk 14]
```diff
@@ -137,91 +137,86 @@ class RecorderWavePainter extends CustomPainter {
...
-            size.height + labelSpacing),
-      ),
-    );
+    final labelDuration = Duration(seconds: i);
+    final durationLineDx = _labelPadding + dragOffset.dx - totalBackDistance.dx;
+    final height = size.height;
+
+    if (labelDuration <
+        Duration(
+            seconds: currentlyRecordedDuration.inSeconds + durationBuffer)) {
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:173]: format!
Also, it may be better to extract the `Duration` object in a separate variable and then use that variable in the condition.

File: lib/src/painters/recorder_wave_painter.dart [hunk 15]
```diff
@@ -137,91 +137,86 @@ class RecorderWavePainter extends CustomPainter {
...
-                (spacing * i) -
-                initialPosition,
-            (waveData[i] * scaleFactor) + size.height - bottomPadding),
-        _wavePaint);
+  void _drawWave(Canvas canvas, Size size, int i) {
+    final halfWidth = size.width / 2;
+    final height = size.height;
+    final dx =
+        -totalBackDistance.dx + dragOffset.dx + (spacing * i) - initialPosition;
+    final scaledWaveHeight = (waveData[i] * scaleFactor);
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:209]: please remove unnecessary use of brackets.

**Review by aditya-css — CHANGES_REQUESTED** [review]

File: lib/src/audio_waveforms.dart [hunk 16]
```diff
@@ -178,4 +185,10 @@ class _AudioWaveformsState extends State<AudioWaveforms> {
       setState(() {});
     });
   }
+
+  void _updateOnControllerUpdate() {
```
Comment (aditya-css) [inline lib/src/audio_waveforms.dart:189]: This name seems ambiguous. Can you please improve it?

File: lib/src/painters/player_wave_painter.dart [hunk 17]
```diff
@@ -92,35 +92,31 @@ class PlayerWavePainter extends CustomPainter {
 
   void _drawWave(Size size, Canvas canvas) {
     final length = waveformData.length;
+    final halfWidth = size.width / 2;
+    final halfHeight = size.height / 2;
```
Comment (aditya-css) [inline lib/src/painters/player_wave_painter.dart:96]: Please prefer multiplication over division. You can use `* 0.5` here instead of `/ 2`.

File: lib/src/painters/recorder_wave_painter.dart [hunk 18]
```diff
@@ -137,91 +137,84 @@ class RecorderWavePainter extends CustomPainter {
   bool shouldRepaint(RecorderWavePainter oldDelegate) => true;
 
   void _drawTextInRange(Canvas canvas, int i, Size size) {
-    if (_labels.isNotEmpty) {
+    if (_labels.isNotEmpty && i < _labels.length) {
+      final label = _labels[i];
+      final content = label.content;
+      final offset = label.offset;
+      final halfWidth = size.width / 2;
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:144]: Please prefer multiplication over division.

File: lib/src/painters/recorder_wave_painter.dart [hunk 19]
```diff
@@ -137,91 +137,84 @@ class RecorderWavePainter extends CustomPainter {
...
+            height + labelSpacing,
+          ),
+        ),
+      );
+    }
     _labelPadding += spacing * updateFrequecy;
   }
 
   void _drawMiddleLine(Canvas canvas, Size size) {
+    final halfWidth = size.width / 2;
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:194]: Please prefer multiplication over division.

File: lib/src/painters/recorder_wave_painter.dart [hunk 20]
```diff
@@ -137,91 +137,84 @@ class RecorderWavePainter extends CustomPainter {
...
-            size.height - bottomPadding),
-        Offset(
-            -totalBackDistance.dx +
-                dragOffset.dx +
-                (spacing * i) -
-                initialPosition,
-            (waveData[i] * scaleFactor) + size.height - bottomPadding),
-        _wavePaint);
+  void _drawWave(Canvas canvas, Size size, int i) {
+    final halfWidth = size.width / 2;
```
Comment (aditya-css) [inline lib/src/painters/recorder_wave_painter.dart:203]: Please prefer multiplication over division.

**Review by aditya-css — CHANGES_REQUESTED** [review]
