### PR TITLE
fix: :bug: IOS Recorder without path not working

### LINKED ISSUE #165: waveData's values close to 0 on iOS
**Describe the bug**
On audio_waveforms: 1.0.2, when call `record()` without specifying a path, we get all waveData's values close to 0. 
- This problem happens on iOS platform
- This problem does not happen on Android platform
- This problem does not happen when we pass a path to record()
- v1.01 does not have this problem

**To Reproduce**
```
    recorderController = RecorderController(useLegacyNormalization: false)
      ..androidEncoder = AndroidEncoder.aac
      ..androidOutputFormat = AndroidOutputFormat.mpeg4
      ..iosEncoder = IosEncoder.kAudioFormatMPEG4AAC
      ..updateFrequency = const Duration(milliseconds: 200)
      ..sampleRate = 44100;

    recorderController.record();

   // then check the recorderControlloer.waveData at recording... all data's value are close to 0
```

**Expected behavior**
recorderControlloer.waveData's value on iOS the same as that of version v1.01

### PR DESCRIPTION
**Pull request by ujas-m-simformsolutions**
This PR fixes #165. Also adds error description for functions.

### CODE REVIEW

File: ios/Classes/AudioRecorder.swift [hunk 1]
```diff
@@ -157,4 +156,15 @@ public class AudioRecorder: NSObject, AVAudioRecorderDelegate{
             return Int(kAudioFormatMPEG4AAC)
         }
     }
+    
+    private func getDocumentDirectory(_ result: @escaping FlutterResult) -> String {
+        let directory = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
```
Comment (aditya-css) [inline ios/Classes/AudioRecorder.swift:161]: NSSearchPathForDirectoriesInDomains can return a path that doesn't even contain the requested directory as stated [here](https://developer.apple.com/documentation/foundation/1414224-nssearchpathfordirectoriesindoma). Please use other method as suggested in "See Also" section of the attached link.

**Review by aditya-css — APPROVED** [review]

**Review by vatsaltanna-simformsolutions — APPROVED** [review]
